baseURL = 'https://blog.jksolbakken.no'
languageCode = 'en-us'
title = 'blog.jksolbakken.no'
theme = "hugo-kiera"

pygmentsCodeFences = true

[author]
    name = "Jan-Kåre Solbakken"
    github = "jksolbakken"
    linkedin = "jksolbakken"

[params]
    tagline = "Ramblings about software and stuff"
    customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode